export const NEWYORK_MOCK_LOCATIONS = [
  {
    hotel: "The Plaza Hotel",
    location: "Manhattan",
    imagePath: "https://source.unsplash.com/_dS27XGgRyQ",
    stars: "5",
    review: "Very good",
    rating: "8.5",
    cost: "88,592",
  },
  {
    hotel: "M Social Hotel Times Square New York",
    location: "Manhattan",
    imagePath: "https://source.unsplash.com/_dS27XGgRyQ",
    stars: "4",
    review: "Very good",
    rating: "8.4",
    cost: "61,307",
  },
  {
    hotel: "JW Marriott Essex House New York",
    location: "Manhattan",
    imagePath: "https://source.unsplash.com/_dS27XGgRyQ",
    stars: "4",
    review: "Very good",
    rating: "8.2",
    cost: "89,560",
  },
  {
    hotel: "The Iroquois New York",
    location: "Manhattan",
    imagePath: "https://source.unsplash.com/_dS27XGgRyQ",
    stars: "4",
    review: "Very good",
    rating: "8.2",
    cost: "70,241",
  },
]
